version: '3'
services:
    db:
        container_name: mysql_db
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'bank'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3307:3306'
        expose: 
            - '3307'
        volumes:
            - ./docker/sql/:/docker-entrypoint-initdb.d
            - ./docker/development/db/:/var/lib/mysql